@host = http://localhost:5254

# Klistra in tokens här efter auth:
@adminToken = PUT_ADMIN_TOKEN_HERE
@studioToken = PUT_STUDIO_TOKEN_HERE

#Id:n som testas
@filmId = 1
@studioId = 1

### Root ###
GET {{host}}/
Accept: application/json

#### ADMIN REGISTER + AUTHENTICATE ####

# Register admin
POST {{host}}/api/users/register
Content-Type: application/json
Accept: application/json

{
    "username": "admin1",
    "password": "pass123",
    "isAdmin": true
}

# Authenticate Admin
POST {{host}}/api/users/authenticate
Content-Type: application/json
Accept: application/json

{
    "username": "admin1",
    "password": "pass123"
}

#### GET ALL STUDIOS (PUBLIC vs ADMIN) ####

# Get all filmstudios (OAUTH => INTE city, INTE RentedFilmCopies)
GET {{host}}/api/filmstudios
Accept: application/json

# Get all filmstudios (ADMIN => full inkl City + RentedFilmCopies)
GET {{host}}/api/filmstudios
Accept: application/json
Authentication: {{adminToken}}

#### GET SINGLE STUDIO (PUBLIC vs SELF vs ADMIN) ####

# Get studio by id (OAUTH => public)
GET {{host}}/api/filmstudio/{{studioId}}
Accept: application/json

# Get studio by id (SELF filmstudio => full)
GET {{host}}/api/filmstudio/{{studioId}}
Accept: application/json
Authentication: {{studioToken}}

# Get studio by id (filmstudio but NOT self => public)
# (Kräver att du registrerar + auth en studio2 och provar mot studioId=1)


#### RENT + RETURN ####

# Rent film (filmstudio-only)
POST {{host}}/api/films/rent?id={{filmId}}&studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}

# Rent with WRONG studioid (ska ej vara en 200)
POST {{host}}/api/films/rent?id={{filmId}}&studioid=999
Accept: application/json
Authentication: {{studioToken}}

# Rent as ADMIN (ska ej vara en 200)
POST {{host}}/api/films/rent?id={{filmId}}&studioid={{studioId}}
Accept: application/json
Authentication: {{adminToken}}

# Rent non-existing film => 409
POST {{host}}/api/films/rent?id=9999&studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}

# Return film (filmstudio-only)
POST {{host}}/api/films/return?id={{filmId}}%studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}

# Return non-existing film => 409
POST {{host}}/api/films/return?id=9999&studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}


#### MY STUDIO RENTALS ####

# My rentals (filmstudio-only)
GET {{host}}/api/mystudio/rentals
Accept: application/json
Authentication: {{studioToken}}

# My rentals without auth => 401

GET {{host}}/api/mystudio/rentals
Accept: application/json