@host = http://localhost:5254
@adminToken = 60af957fb7654ee0b396e6828f5ef070
@studioToken = PUT_TOKEN_HERE
@filmId = 1
@studioId = 1


### Root
GET {{host}}/
Accept: application/json

### Register admin 
POST {{host}}/api/users/register
Content-Type: application/json
Accept: application/json

{
    "username": "admin1",
    "password": "pass123",
    "isAdmin": true
}

### Authenticate admin 
POST {{host}}/api/users/authenticate
Content-Type: application/json
Accept: application/json

{
    "username": "admin1",
    "password": "pass123"
}

### Create film (admin)
POST {{host}}/api/films
Accept: application/json
Content-Type: application/json
Authentication: {{adminToken}}


### Get films (public)
GET {{host}}/api/films
Accept: application/json

### Register filmstudio 
POST {{host}}/api/filmstudio/register
Content-Type: application/json
Accept: application/json

{
    "name": "Studio One",
    "city": "Stockholm",
    "username": "studio1",
    "password": "pass123"
}

### Authenticate filmstudio 
POST {{host}}/api/users/authenticate
Content-Type: application/json
Accept: application/json

{
    "username": "studio1",
    "password": "pass123"
}

### Rent 
POST {{host}}/api/films/rent?id={{filmId}}&studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}

### Return 
POST {{host}}/api/films/return?id={{filmId}}&studioid={{studioId}}
Accept: application/json
Authentication: {{studioToken}}

### My rentals 
GET {{host}}/api/mystudio/rentals
Accept: application/json
Authentication: {{studioToken}}